version: '3'

services:

  backend:
    build: ./opalytica
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./opalytica:/src/backend/
    ports:
      - 8000:8000

  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/src/website/
    ports:
      - 3000:3000
    depends_on:
      - backend
    links:
      - backend

  